### ISSUE TITLE
Function hang

### ISSUE THREAD

**Issue by Mchapuis** [Mchapuis/COMP354#14]
This "hang"
```
String str_test_ParseAbility = "Pikachu:pokemon:cat:basic:cat:lightning:60:retreat:cat:colorless:1:attacks:cat:colorless:1:5,cat:colorless:2:6";
Ability ab_test = new test();
final Ability ab_new = ab_test.parseAbilitiesLine(str_test_ParseAbility);
HumanPlayer hp = new HumanPlayer();
		
// the function need to return the name at least
String name = ab_new.name;
assertNotNull(name);
````

And here is the Call stack when I pause the program
![image](https://cloud.githubusercontent.com/assets/4071667/26663623/fe8f76cc-4659-11e7-885e-30ef3884076f.png)

Another thread open:
![image](https://cloud.githubusercontent.com/assets/4071667/26663662/2c433540-465a-11e7-8d19-d067ca6066fc.png)

**Comment by ananarchie** [comment]
i didn't write the original function but it looks like you're trying to parse a pokemon as an ability, is this what you intended to do?

**Comment by Mchapuis** [comment]
Frank said the same thing, I changed it but the error was the same
